Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - app/assets/**/*
    - bin/*
    - db/*schema.rb
    - log/**/*
    - public/**/*
    - storage/**/*